models:

# hyperclova-seed models
  - name: hyperclova-seed-vision-3b
    repo_id: naver-hyperclovax/HyperCLOVAX-SEED-Vision-Instruct-3B
    revision: main
    target_dir: ai_model_dir/hf/hyperclova-seed-vision-3b

  - name: hyperclova-seed-text-1.5b
    repo_id: naver-hyperclovax/HyperCLOVAX-SEED-Text-Instruct-1.5B
    revision: main
    target_dir: ai_model_dir/hf/hyperclova-seed-text-1.5b

  - name: hyperclova-seed-text-0.5b
    repo_id: naver-hyperclovax/HyperCLOVAX-SEED-Text-Instruct-0.5B
    revision: main
    target_dir: ai_model_dir/hf/hyperclova-seed-text-0.5b

# kakana-nano models
  - name: kanana-nano-2.1b-base
    repo_id: kakaocorp/kanana-nano-2.1b-base
    revision: main
    target_dir: ai_model_dir/hf/kanana-nano-2.1b-base

  - name: kanana-nano-2.1b-instruct
    repo_id: kakaocorp/kanana-nano-2.1b-instruct
    revision: main
    target_dir: ai_model_dir/hf/kanana-nano-2.1b-instruct

  - name: kanana-nano-2.1b-embedding
    repo_id: kakaocorp/kanana-nano-2.1b-embedding
    revision: main
    target_dir: ai_model_dir/hf/kanana-nano-2.1b-embedding

# qwen models
  - name: qwen3-1.7b-base
    repo_id: Qwen/Qwen3-1.7B-Base
    revision: main
    target_dir: ai_model_dir/hf/qwen3-1.7b-base

  - name: qwen3-0.6b-base
    repo_id: Qwen/Qwen3-0.6B-Base
    revision: main
    target_dir: ai_model_dir/hf/qwen3-0.6b-base

# BGE-m3-ko models
  - name: BGE-m3-ko
    repo_id: dragonkue/BGE-m3-ko
    revision: main
    target_dir: ai_model_dir/hf/BGE-m3-ko
